
name: Auto commit

on:
  schedule:
    - cron: '0 6-8 * * *'

jobs:
  auto_commit:
    # Run the job on ubuntu-latest
    runs-on: ubuntu-latest
    # Define the steps
    steps:
      # Set global directory
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      # Checkout the repository
      - uses: actions/checkout@v3     
        with:
         persist-credentials: false
         fetch-depth: 1
      # Modify last update file
      - name: Modify last update
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED          
      # Commit changes
      - name: Commit changes
        run: |
          git config --local user.email "rudiansyahether@gmail.com"
          git config --local user.name "lypsisrudiansyah"
          git add -A
          git commit -m "reforestation process"          
      # Push changes to GitHub
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          branch: main
          github_token: ${{ secrets.THE_GHUB_TOKEN }}
